# import

In [1]:
from tqsdk.tafunc import ma, ema, abs, std, hhv, llv, count, time_to_datetime, barlast

在使用天勤量化之前，默认您已经知晓并同意以下免责条款，如果不同意请立即停止使用：https://www.shinnytech.com/blog/disclaimer/

In [2]:
%run CommonUtil.ipynb

In [3]:
%run tradeUtil.ipynb

In [4]:
%run backTestUtil.ipynb

In [5]:
%run paraConfig.ipynb

In [6]:
path = './data/IC2512.csv'

In [7]:
import warnings
warnings.simplefilter(action='ignore',category=pd.errors.PerformanceWarning)

In [41]:
data = prepare_back_test_data(path,para)

In [9]:
data.head(5)

,open,high,low,close,volume,hhmm,opening_day,end_day,opening_night,vol_prev,...,peak4_prev1_bias,valley1_prev1_bias,valley2_prev1_bias,valley3_prev1_bias,valley4_prev1_bias,tl_price,jl_price,long,stop_loss_long,sell
time,,,,,,,,,,,,,,,,,,,,,
2025-07-09 13:05:00,5718.0,5728.6,5716.2,5725.4,269,13:05,False,False,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0
2025-07-09 13:10:00,5725.8,5726.2,5722.2,5724.6,127,13:10,False,False,False,269.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0
2025-07-09 13:15:00,5723.6,5729.6,5723.2,5728.0,107,13:15,False,False,False,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0
2025-07-09 13:20:00,5727.2,5728.6,5723.4,5727.0,114,13:20,False,False,False,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0
2025-07-09 13:25:00,5726.8,5728.2,5724.4,5728.0,86,13:25,False,False,False,114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0

# 2025-10-17 09:40:00

In [17]:
data.loc['2025-10-17 09:40:00'][['kl_ma13','kl_ma35','ma_category_s','ma_category_m','ma_category_l']]

kl_ma13          1.0
kl_ma35          0.0
ma_category_s    3.0
ma_category_m    1.0
ma_category_l    1.0
Name: 2025-10-17 09:40:00, dtype: object

In [19]:
data.loc['2025-10-17 09:40:00'][['bias1','bias2']]

bias1    -0.912
bias2   -1.8271
Name: 2025-10-17 09:40:00, dtype: object

In [23]:
data.loc['2025-10-17 09:35:00'][['z_pct_curr1','z_pct_curr2']]

z_pct_curr1    8.259049
z_pct_curr2    8.259049
Name: 2025-10-17 09:35:00, dtype: object

In [27]:
data.loc['2025-10-17 09:35:00'][['peak1','peak2','p_prev1_1','p_prev1_2']]
# zig 0.2: 上涨
# ZIG 0.3: 反弹

peak1        7080.6
peak2        7080.6
p_prev1_1    7042.4
p_prev1_2    7141.4
Name: 2025-10-17 09:35:00, dtype: object

In [32]:
# 长上影
data.loc['2025-10-17 09:35:00':'2025-10-17 09:40:00'][['k_ups','k_lows','ma_ups','ma_lows']]

                     k_ups  k_lows  ma_ups  ma_lows
time
2025-10-17 09:35:00    3.2    13.8    6.11     5.01
2025-10-17 09:40:00   18.8     2.6    6.70     4.85

In [38]:
# 
data.loc['2025-10-17 09:35:00':'2025-10-17 09:40:00'][['pct_chg','ma_pct','mv_stage']]

                     pct_chg   ma_pct  mv_stage
time
2025-10-17 09:35:00    2.634  1.23000         2
2025-10-17 09:40:00   -2.005  1.33025         2

In [42]:
data.loc['2025-10-17 09:35:00':'2025-10-17 09:40:00'][['mv1','mv2','mv3','mv_stage']]

                             mv1          mv2          mv3  mv_stage
time
2025-10-17 09:35:00  2194.338876  1864.272103  2049.856476         3
2025-10-17 09:40:00  2309.549989  1911.283220  2057.599198         3