In [1]:
import QUANTAXIS as QA
import pandas as pd
import tushare as ts
import numpy as np
# import TA-Lib as ta
import scipy.signal as signal
import matplotlib.pyplot as plt

In [7]:
DF_Blk_Data = QA.QA_fetch_index_day_adv('880472','2024-05-01','2024-05-24')

In [9]:
DF_Blk_Data.data

,,open,close,high,low,vol,amount,up_count,down_count,date_stamp,volume
date,code,,,,,,,,,,
2024-05-06,880472,1291.87,1281.22,1301.25,1275.64,370348.0,3.361923e+10,33,13,1.714925e+09,370348.0
2024-05-07,880472,1277.98,1277.62,1284.53,1270.69,271943.0,2.513603e+10,8,38,1.715011e+09,271943.0
2024-05-08,880472,1273.88,1260.27,1274.81,1259.17,205737.0,1.865216e+10,2,48,1.715098e+09,205737.0
2024-05-09,880472,1261.68,1269.16,1276.99,1261.68,239205.0,2.110803e+10,46,4,1.715184e+09,239205.0
2024-05-10,880472,1269.46,1279.55,1283.52,1266.30,279523.0,2.441958e+10,47,3,1.715270e+09,279523.0
2024-05-13,880472,1274.15,1283.60,1293.22,1262.20,324529.0,2.785416e+10,28,16,1.715530e+09,324529.0
2024-05-14,880472,1282.44,1290.49,1290.95,1272.26,297919.0,2.551309e+10,39,7,1.715616e+09,297919.0
2024-05-15,880472,1296.46,1254.24,1297.04,1253.52,381432.0,3.196263e+10,2,49,1.715702e+09,381432.0
2024-05-16,880472,1258.46,1254.23,1269.77,1251.26,257250.0,2.208211e+10,15,28,1.715789e+09,257250.0
2024-05-17,880472,1252.35,1272.30,1272.63,1248.92,263601.0,2.365107e+10,47,4,1.715875e+09,263601.0
2024-05-20,880472,1270.16,1273.13,1287.87,1269.43,269574.0,2.490073e+10,17,30,1.716134e+09,269574.0
2024-05-21,880472,1270.37,1265.84,1275.08,1261.48,167513.0,1.503943e+10,1,50,1.716221e+09,167513.0
2024-05-22,880472,1263.84,1268.71,1274.25,1260.68,169517.0,1.514213e+10,37,8,1.716307e+09,169517.0
2024-05-23,880472,1264.75,1243.28,1265.21,1242.05,233539.0,2.036517e+10,1,50,1.716394e+09,233539.0
2024-05-24,880472,1239.64,1226.42,1245.08,1225.74,169956.0,1.512030e+10,0,51,1.716480e+09,169956.0

In [20]:
idx_list = QA.QA_fetch_index_list_adv()

In [21]:
#只获取板块/概念指数
idx_name = idx_list['880301':'880981'].name
# idx_wanted.to_csv('all_blk.csv',encoding='utf_8_sig')
#所有行业指数名
industry_name = idx_name['880301':'880497']
#所有概念指数名
concept_name = idx_name['880501':'880981']
idx_name.head(5)

code
880301      煤炭
880302    煤炭开采
880303    焦炭加工
880305      电力
880306    水力发电
Name: name, dtype: object

In [26]:
all_blk_component = QA.QA_fetch_stock_block_adv().view_block

In [27]:
type(all_blk_component)

blockname
300ESG    [000001, 000002, 000063, 000066, 000069, 00010...
300周期     [000001, 000002, 000069, 000166, 000617, 00070...
300非周     [000063, 000100, 000157, 000301, 000333, 00033...
3D打印      [000837, 000928, 000969, 000988, 001296, 00136...
5G概念      [000004, 000049, 000063, 000066, 000070, 00015...
                                ...
黄酒                                 [600059, 600616, 601579]
黄金        [000506, 000975, 001337, 002155, 002237, 30013...
黄金ETF     [0159812, 0159830, 0159831, 0159834, 0159934, ...
黄金主题基金    [33,000929, 33,000930, 33,019005, 33,159812, 3...
黄金概念      [000009, 000017, 000025, 000060, 000408, 00041...
Length: 1281, dtype: object

In [40]:
df_all_blk = all_blk_component.to_frame(name='component')

In [36]:
df_idx_name = industry_name.to_frame()

In [43]:
df_idx_compoent = pd.merge(df_all_blk,df_idx_name,left_index=True,right_on='name')

In [44]:
df_idx_compoent

                                                component  name
code
880489  [000066, 000938, 000977, 000997, 001229, 00133...  IT设备
880445  [000519, 000551, 000584, 000856, 000880, 00098...  专用机械
880403  [000423, 000538, 000590, 000623, 000650, 00079...   中成药
880373  [001318, 002329, 002570, 002719, 002732, 00291...   乳制品
880494  [000676, 000681, 000971, 002095, 002115, 00212...   互联网
...                                                   ...   ...
880471  [000001, 001227, 002142, 002807, 002839, 00293...    银行
880345           [002162, 002918, 003012, 300234, 300285]    陶瓷
880375  [000505, 000523, 000529, 000639, 000716, 00089...    食品
880364  [000702, 000876, 001313, 001366, 002100, 00231...    饲料
880328  [000506, 000975, 001337, 002155, 002237, 30013...    黄金

[110 rows x 2 columns]

In [31]:
all_blk_component.index

Index(['300ESG', '300周期', '300非周', '3D打印', '5G概念', '6G概念', 'AIGC概念', 'AI手机PC',
       'BC电池', 'BIPV概念',
       ...
       '高贝塔值', '高负债率', '高质押股', '高速公路', '鸡肉', '黄酒', '黄金', '黄金ETF', '黄金主题基金',
       '黄金概念'],
      dtype='object', name='blockname', length=1281)

In [33]:
industry_name.values

array(['煤炭', '煤炭开采', '焦炭加工', '电力', '水力发电', '火力发电', '新型电力', '石油', '石油开采',
       '石油加工', '石油贸易', '钢铁', '普钢', '特种钢', '钢加工', '有色', '铜', '铝', '铅锌',
       '黄金', '小金属', '化纤', '化工', '化工原料', '农药化肥', '塑料', '橡胶', '染料涂料', '建材',
       '陶瓷', '水泥', '玻璃', '其他建材', '造纸', '矿物制品', '日用化工', '农林牧渔', '种植业',
       '渔业', '林业', '饲料', '农业综合', '纺织服饰', '纺织', '服饰', '食品饮料', '乳制品', '软饮料',
       '食品', '酿酒', '白酒', '啤酒', '红黄酒', '家用电器', '汽车类', '汽车整车', '汽车配件',
       '汽车服务', '摩托车', '医疗保健', '家居用品', '医药', '化学制药', '生物制药', '中成药', '商业连锁',
       '百货', '超市连锁', '电器连锁', '医药商业', '其他商业', '商品城', '批发业', '商贸代理', '传媒娱乐',
       '出版业', '影视音像', '广告包装', '文教休闲', '酒店餐饮', '旅游', '旅游服务', '旅游景点', '航空',
       '船舶', '运输设备', '通用机械', '机床制造', '机械基件', '工业机械', '化工机械', '轻工机械',
       '纺织机械', '农用机械', '专用机械', '电气设备', '工程机械', '电器仪表', '电信运营', '公共交通',
       '水务', '供气供热', '环境保护', '运输服务', '铁路', '水运', '空运', '公路', '仓储物流',
       '交通设施', '路桥', '机场', '港口', '银行', '证券', '保险', '多元金融', '建筑', '建筑工程',
       '装修装饰', '房地产', '全国地产', '区域地产', '园区开发', '房产服务', 'IT设备', '通信设备',
       '半导体', '元器件', '软件服务', '互联网', '综合类'], dtype=object)